import type { Metadata } from "next";
import "./globals.css";
import ClientProviders from "./provaider";
import Header from "./components/header";
import { ToastContainer } from "react-toastify";
import Navbar from "./components/navbar";
import "primereact/resources/themes/lara-light-cyan/theme.css";

export const metadata: Metadata = {
  title: "famelinmodayazici",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr" className="h-full">
      <body>
        <ClientProviders>
          <div className="">
            <Header />
            <Navbar></Navbar>
          </div>
          <div>{children}</div>
        </ClientProviders>
        <ToastContainer
          position="bottom-right"
          hideProgressBar
          theme="colored"
        />
      </body>
    </html>
  );
}
