import type { Metadata } from "next";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "primereact/resources/themes/lara-light-cyan/theme.css";
import ConditionalLayout from "./conditionalLayout";

// client component'i buraya import et

export const metadata: Metadata = {
  title: "famelinmodayazici",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr" className="h-full">
      <body className="flex flex-col min-h-screen">
        <ConditionalLayout>{children}</ConditionalLayout>

        <ToastContainer
          position="bottom-right"
          hideProgressBar
          theme="colored"
        />
      </body>
    </html>
  );
}
